In [3]:
#Run the file without any changes
import pandas as pd
import numpy as np
from numbers import Number
from matplotlib import pyplot as plt

# Objective of the Project
-Determine whether to invest in commercial or private aeroplanes
-Determine the risks associated with each option for investment
-Determine the optimal decision to invest in the commercial or private aeroplanes
# Overview of the Project
This project provides an analysis of investing in the purchase of airplanes for commercial or private use. The project shall analyse the number of accidents in the aviation industry related to the type of airplanes that caused them. This shall then be linked to the geographical location in which the planes will operate and provide strategies to minimise the accidents in comparison to the weather patterns of the region.

# Business understanding
The aviation sector has various drivers that impact on the business. For an investment to be undertaken, the investor must understand the model/type of aircraft to be bought, the geographical location of operation, the number of accidents the model has been involved in, and the fatalities and the region's weather patterns.  Moreover, the analysis of fatalities will provide insight into the accident and its impact on the operations of commercial or private planes.

In [5]:

df=pd.read_csv('AviationData.csv',nrows=100,skiprows=0)
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [6]:
df.dtypes

Event.Id                   object
Investigation.Type         object
Accident.Number            object
Event.Date                 object
Location                   object
Country                    object
Latitude                  float64
Longitude                 float64
Airport.Code               object
Airport.Name               object
Injury.Severity            object
Aircraft.damage            object
Aircraft.Category          object
Registration.Number        object
Make                       object
Model                      object
Amateur.Built              object
Number.of.Engines         float64
Engine.Type                object
FAR.Description            object
Schedule                   object
Purpose.of.flight          object
Air.carrier                object
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition          object
Broad.phase.of.flight      object
Report.Status              object
Publication.Date           object
dtype: object

In [7]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                100 non-null    object
 1   Investigation.Type      100 non-null    object
 2   Accident.Number         100 non-null    object
 3   Event.Date              100 non-null    object
 4   Location                100 non-null    object
 5   Country                 99 non-null     object
 6   Latitude                2 non-null      float64
 7   Longitude               2 non-null      float64
 8   Airport.Code            44 non-null     object
 9   Airport.Name            59 non-null     object
 10  Injury.Severity         100 non-null    object
 11  Aircraft.damage         99 non-null     object
 12  Aircraft.Category       89 non-null     object
 13  Registration.Number     100 non-null    object
 14  Make                    100 non-null    object
 15  Model                   100 non-null    object
 16  Amateur.Built           100 non-null    object
 17  Number.of.Engines       99 non-null     float64
 18  Engine.Type             99 non-null     object
 19  FAR.Description         89 non-null     object
 20  Schedule                16 non-null     object
 21  Purpose.of.flight       99 non-null     object
 22  Air.carrier             15 non-null     object
 23  Total.Fatal.Injuries    98 non-null     float64
 24  Total.Serious.Injuries  97 non-null     float64
 25  Total.Minor.Injuries    97 non-null     float64
 26  Total.Uninjured         99 non-null     float64
 27  Weather.Condition       100 non-null    object
 28  Broad.phase.of.flight   100 non-null    object
 29  Report.Status           100 non-null    object
 30  Publication.Date        99 non-null     object
dtypes: float64(7), object(24)
memory usage: 24.3+ KB

In [9]:
#determine the null values in the dataframe
df.isna()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,True,...,False,True,False,True,True,True,False,False,False,False
3,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,True,True,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,True,True,False,False,...,False,True,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,True,True,False,False,...,False,True,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,True,True,False,False,...,False,True,False,False,False,False,False,False,False,False

In [10]:
#determine the number of missing data.The number with zero entries contain valid data while the rest are missing i.e latitude is missing 98 values.
df.isna().sum()

Event.Id                   0
Investigation.Type         0
Accident.Number            0
Event.Date                 0
Location                   0
Country                    1
Latitude                  98
Longitude                 98
Airport.Code              56
Airport.Name              41
Injury.Severity            0
Aircraft.damage            1
Aircraft.Category         11
Registration.Number        0
Make                       0
Model                      0
Amateur.Built              0
Number.of.Engines          1
Engine.Type                1
FAR.Description           11
Schedule                  84
Purpose.of.flight          1
Air.carrier               85
Total.Fatal.Injuries       2
Total.Serious.Injuries     3
Total.Minor.Injuries       3
Total.Uninjured            1
Weather.Condition          0
Broad.phase.of.flight      0
Report.Status              0
Publication.Date           1
dtype: int64

In [11]:
#Drop accidents with 90% of data missing
df_1 = df.dropna(axis=1,thresh=int(.90*len(df)))
df_1

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Injury.Severity,Aircraft.damage,Registration.Number,Make,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,Fatal(2),Destroyed,NC6404,Stinson,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,Fatal(4),Destroyed,N5069P,Piper,...,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,Fatal(3),Destroyed,N5142R,Cessna,...,Reciprocating,Personal,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,Fatal(2),Destroyed,N1168J,Rockwell,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,Fatal(1),Destroyed,N15NY,Cessna,...,NaN,Personal,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,20020917X01625,Accident,ANC82DA015,1982-01-15,"NEAR NUIQSUT, AK",United States,Non-Fatal,Substantial,N1459T,De Havilland,...,Turbo Prop,Unknown,0.0,0.0,0.0,4.0,VMC,Landing,Probable Cause,15-01-1983
96,20020917X02096,Accident,FTW82FA041,1982-01-16,"HOUMA, LA",United States,Fatal(1),Destroyed,N1081H,Bell Helicopter,...,Turbo Shaft,Unknown,1.0,2.0,0.0,0.0,IMC,Cruise,Probable Cause,16-01-1983
97,20020917X02487,Accident,NYC82DA023,1982-01-16,"SWANTON, VT",United States,Non-Fatal,Substantial,N704KE,Cessna,...,Reciprocating,Personal,0.0,0.0,0.0,1.0,VMC,Go-around,Probable Cause,16-01-1983
98,20020917X02321,Accident,LAX82FVG14,1982-01-17,"DAVIS, CA",United States,Fatal(1),Destroyed,N63182,Cessna,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,17-01-1983
99,20020917X02306,Accident,LAX82FUQ08,1982-01-17,"MOJAVE, CA",United States,Fatal(1),Destroyed,N381JH,Bede Aircraft,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,VMC,Maneuvering,Probable Cause,17-01-1983

In [12]:
df_1.isna().mean().mul(100).round(0)

Event.Id                  0.0
Investigation.Type        0.0
Accident.Number           0.0
Event.Date                0.0
Location                  0.0
Country                   1.0
Injury.Severity           0.0
Aircraft.damage           1.0
Registration.Number       0.0
Make                      0.0
Model                     0.0
Amateur.Built             0.0
Number.of.Engines         1.0
Engine.Type               1.0
Purpose.of.flight         1.0
Total.Fatal.Injuries      2.0
Total.Serious.Injuries    3.0
Total.Minor.Injuries      3.0
Total.Uninjured           1.0
Weather.Condition         0.0
Broad.phase.of.flight     0.0
Report.Status             0.0
Publication.Date          1.0
dtype: float64

In [13]:
# replace the missing data in every column with categorical data and continuous data

In [14]:
df_2 = df_1.fillna({"Country":"UNKNOWN","Aircraft.damage":"UNKNOWN","Aircraft.Category":"UNKNOWN","Number.of.Engines":"UNKNOWN","Engine.Type":"UNKWOWN","Purpose.of.flight":"UNKWOWN","Publication.Date":"UNKNOWN" })
df_2

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Injury.Severity,Aircraft.damage,Registration.Number,Make,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,Fatal(2),Destroyed,NC6404,Stinson,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,UNKNOWN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,Fatal(4),Destroyed,N5069P,Piper,...,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,Fatal(3),Destroyed,N5142R,Cessna,...,Reciprocating,Personal,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,Fatal(2),Destroyed,N1168J,Rockwell,...,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,Fatal(1),Destroyed,N15NY,Cessna,...,UNKWOWN,Personal,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,20020917X01625,Accident,ANC82DA015,1982-01-15,"NEAR NUIQSUT, AK",United States,Non-Fatal,Substantial,N1459T,De Havilland,...,Turbo Prop,Unknown,0.0,0.0,0.0,4.0,VMC,Landing,Probable Cause,15-01-1983
96,20020917X02096,Accident,FTW82FA041,1982-01-16,"HOUMA, LA",United States,Fatal(1),Destroyed,N1081H,Bell Helicopter,...,Turbo Shaft,Unknown,1.0,2.0,0.0,0.0,IMC,Cruise,Probable Cause,16-01-1983
97,20020917X02487,Accident,NYC82DA023,1982-01-16,"SWANTON, VT",United States,Non-Fatal,Substantial,N704KE,Cessna,...,Reciprocating,Personal,0.0,0.0,0.0,1.0,VMC,Go-around,Probable Cause,16-01-1983
98,20020917X02321,Accident,LAX82FVG14,1982-01-17,"DAVIS, CA",United States,Fatal(1),Destroyed,N63182,Cessna,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,17-01-1983
99,20020917X02306,Accident,LAX82FUQ08,1982-01-17,"MOJAVE, CA",United States,Fatal(1),Destroyed,N381JH,Bede Aircraft,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,VMC,Maneuvering,Probable Cause,17-01-1983

In [15]:
df_2.isna().mean().mul(100).round(0)

Event.Id                  0.0
Investigation.Type        0.0
Accident.Number           0.0
Event.Date                0.0
Location                  0.0
Country                   0.0
Injury.Severity           0.0
Aircraft.damage           0.0
Registration.Number       0.0
Make                      0.0
Model                     0.0
Amateur.Built             0.0
Number.of.Engines         0.0
Engine.Type               0.0
Purpose.of.flight         0.0
Total.Fatal.Injuries      2.0
Total.Serious.Injuries    3.0
Total.Minor.Injuries      3.0
Total.Uninjured           1.0
Weather.Condition         0.0
Broad.phase.of.flight     0.0
Report.Status             0.0
Publication.Date          0.0
dtype: float64

# Establish the relationship between the severity of the injuries, how the aeroplane is damaged and the Total.Serious.Injuries, Total.Minor.Injuries, Total.Uninjured

In [17]:
df_2.groupby(['Injury.Severity','Aircraft.damage'])['Total.Minor.Injuries'].mean()

Injury.Severity  Aircraft.damage
Fatal(1)         Destroyed          0.090909
Fatal(2)         Destroyed          0.000000
Fatal(3)         Destroyed          0.000000
Fatal(4)         Destroyed          0.250000
Fatal(78)        Destroyed          3.000000
Fatal(8)         Destroyed          0.000000
Incident         Minor              0.000000
                 UNKNOWN            0.000000
Non-Fatal        Destroyed          0.625000
                 Substantial        0.350877
Name: Total.Minor.Injuries, dtype: float64

In [18]:
df_2.groupby(['Injury.Severity','Aircraft.damage'])['Total.Fatal.Injuries'].mean()

Injury.Severity  Aircraft.damage
Fatal(1)         Destroyed           1.0
Fatal(2)         Destroyed           2.0
Fatal(3)         Destroyed           3.0
Fatal(4)         Destroyed           4.0
Fatal(78)        Destroyed          78.0
Fatal(8)         Destroyed           8.0
Incident         Minor               0.0
                 UNKNOWN             0.0
Non-Fatal        Destroyed           0.0
                 Substantial         0.0
Name: Total.Fatal.Injuries, dtype: float64

In [19]:
df_2.groupby(['Injury.Severity','Aircraft.damage'])['Total.Uninjured'].mean()

Injury.Severity  Aircraft.damage
Fatal(1)         Destroyed            0.000000
Fatal(2)         Destroyed            0.000000
Fatal(3)         Destroyed            0.000000
Fatal(4)         Destroyed            0.000000
Fatal(78)        Destroyed            0.000000
Fatal(8)         Destroyed            0.000000
Incident         Minor                1.333333
                 UNKNOWN            149.000000
Non-Fatal        Destroyed            1.000000
                 Substantial          2.465517
Name: Total.Uninjured, dtype: float64

In [20]:
df_2.groupby(['Purpose.of.flight','Injury.Severity'])[['Total.Fatal.Injuries','Total.Uninjured','Total.Minor.Injuries']].mean()

                                     Total.Fatal.Injuries  Total.Uninjured  \
Purpose.of.flight   Injury.Severity
Business            Fatal(1)                          1.0         0.000000
                    Fatal(3)                          3.0         0.000000
                    Fatal(8)                          8.0         0.000000
                    Incident                          0.0         1.000000
                    Non-Fatal                         0.0         2.400000
Executive/corporate Non-Fatal                         0.0         3.000000
Ferry               Non-Fatal                         0.0         1.000000
Instructional       Non-Fatal                         0.0         1.333333
Personal            Fatal(1)                          1.0         0.000000
                    Fatal(2)                          2.0         0.000000
                    Fatal(3)                          3.0         0.000000
                    Fatal(4)                          4.0         0.000000
                    Incident                          0.0         1.000000
                    Non-Fatal                         0.0         1.416667
UNKWOWN             Non-Fatal                         NaN        44.000000
Unknown             Fatal(1)                          1.0         0.000000
                    Fatal(2)                          2.0         0.000000
                    Fatal(78)                        78.0         0.000000
                    Incident                          0.0        75.500000
                    Non-Fatal                         0.0         2.066667

                                     Total.Minor.Injuries
Purpose.of.flight   Injury.Severity
Business            Fatal(1)                     1.000000
                    Fatal(3)                     0.000000
                    Fatal(8)                     0.000000
                    Incident                     0.000000
                    Non-Fatal                    0.000000
Executive/corporate Non-Fatal                    0.000000
Ferry               Non-Fatal                    0.000000
Instructional       Non-Fatal                    0.000000
Personal            Fatal(1)                     0.000000
                    Fatal(2)                     0.000000
                    Fatal(3)                     0.000000
                    Fatal(4)                     0.250000
                    Incident                     0.000000
                    Non-Fatal                    0.542857
UNKWOWN             Non-Fatal                    1.000000
Unknown             Fatal(1)                     0.000000
                    Fatal(2)                     0.000000
                    Fatal(78)                    3.000000
                    Incident                     0.000000
                    Non-Fatal                    0.333333

# Establish the relationship between the weather conditions and injuries recorded

In [22]:
df_2.groupby(['Weather.Condition','Injury.Severity'])[['Total.Fatal.Injuries','Total.Uninjured','Total.Minor.Injuries']].mean()

                                   Total.Fatal.Injuries  Total.Uninjured  \
Weather.Condition Injury.Severity
IMC               Fatal(1)                          1.0         0.000000
                  Fatal(2)                          2.0         0.000000
                  Fatal(3)                          3.0         0.000000
                  Fatal(4)                          4.0         0.000000
                  Fatal(78)                        78.0         0.000000
                  Fatal(8)                          8.0         0.000000
                  Non-Fatal                         0.0         1.125000
UNK               Fatal(2)                          2.0         0.000000
                  Fatal(4)                          4.0         0.000000
                  Incident                          0.0       149.000000
                  Non-Fatal                         0.0         0.000000
VMC               Fatal(1)                          1.0         0.000000
                  Fatal(2)                          2.0         0.000000
                  Fatal(3)                          3.0         0.000000
                  Fatal(4)                          4.0         0.000000
                  Incident                          0.0         1.333333
                  Non-Fatal                         0.0         2.535714

                                   Total.Minor.Injuries
Weather.Condition Injury.Severity
IMC               Fatal(1)                     0.000000
                  Fatal(2)                     0.000000
                  Fatal(3)                     0.000000
                  Fatal(4)                     0.500000
                  Fatal(78)                    3.000000
                  Fatal(8)                     0.000000
                  Non-Fatal                    0.500000
UNK               Fatal(2)                     0.000000
                  Fatal(4)                     0.000000
                  Incident                     0.000000
                  Non-Fatal                    1.500000
VMC               Fatal(1)                     0.250000
                  Fatal(2)                     0.000000
                  Fatal(3)                     0.000000
                  Fatal(4)                     0.000000
                  Incident                     0.000000
                  Non-Fatal                    0.327273

# Establish the relationship between the make of the aeroplane,engine type and the injuries recorded

In [24]:
df_2.groupby(['Make','Engine.Type','Injury.Severity'])[['Total.Fatal.Injuries','Total.Uninjured','Total.Minor.Injuries']].mean()

                                                 Total.Fatal.Injuries  \
Make              Engine.Type   Injury.Severity
Aerospatiale      Turbo Shaft   Non-Fatal                         0.0
Air Tractor       Reciprocating Non-Fatal                         0.0
Bede Aircraft     Reciprocating Fatal(1)                          1.0
Beech             Reciprocating Fatal(2)                          2.0
                                Non-Fatal                         0.0
Beechcraft        Reciprocating Fatal(1)                          1.0
Bell              Turbo Shaft   Non-Fatal                         0.0
Bell Helicopter   Turbo Shaft   Fatal(1)                          1.0
Bellanca          Reciprocating Non-Fatal                         0.0
Boeing            Reciprocating Non-Fatal                         0.0
                  Turbo Fan     Fatal(78)                        78.0
Cessna            Reciprocating Fatal(1)                          1.0
                                Fatal(2)                          2.0
                                Fatal(3)                          3.0
                                Fatal(4)                          4.0
                                Fatal(8)                          8.0
                                Non-Fatal                         0.0
                  UNKWOWN       Fatal(1)                          1.0
Curtis            Reciprocating Non-Fatal                         0.0
De Havilland      Turbo Prop    Non-Fatal                         0.0
Embraer           Turbo Prop    Incident                          0.0
Enstrom           Reciprocating Non-Fatal                         0.0
Grumman           Reciprocating Fatal(2)                          2.0
                                Non-Fatal                         0.0
Hughes            Reciprocating Non-Fatal                         0.0
Lockheed          Turbo Fan     Incident                          0.0
Maule             Reciprocating Non-Fatal                         0.0
Mcdonnell Douglas Turbo Fan     Non-Fatal                         NaN
Mooney            Reciprocating Fatal(1)                          1.0
                                Non-Fatal                         0.0
Navion            Reciprocating Fatal(1)                          1.0
                                Fatal(3)                          3.0
North American    Reciprocating Non-Fatal                         0.0
Piper             Reciprocating Fatal(1)                          1.0
                                Fatal(2)                          2.0
                                Fatal(4)                          4.0
                                Incident                          0.0
                                Non-Fatal                         0.0
Quickie           Reciprocating Non-Fatal                         0.0
Rockwell          Reciprocating Fatal(2)                          2.0
                                Incident                          0.0
Schleicher        Unknown       Non-Fatal                         0.0
Smith             Reciprocating Non-Fatal                         0.0
Stinson           Reciprocating Fatal(2)                          2.0
Swearingen        Turbo Prop    Non-Fatal                         0.0

                                                 Total.Uninjured  \
Make              Engine.Type   Injury.Severity
Aerospatiale      Turbo Shaft   Non-Fatal               6.000000
Air Tractor       Reciprocating Non-Fatal               1.000000
Bede Aircraft     Reciprocating Fatal(1)                0.000000
Beech             Reciprocating Fatal(2)                0.000000
                                Non-Fatal               2.000000
Beechcraft        Reciprocating Fatal(1)                0.000000
Bell              Turbo Shaft   Non-Fatal               1.000000
Bell Helicopter   Turbo Shaft   Fatal(1)                0.000000
Bellanca          Reciprocating Non-Fatal               0.000000
Boeing            Reciprocating Non-Fatal               1.000000
                  Turbo Fan     Fatal(78)               0.000000
Cessna            Reciprocating Fatal(1)                0.000000
                                Fatal(2)                0.000000
                                Fatal(3)                0.000000
                                Fatal(4)                0.000000
                                Fatal(8)                0.000000
                                Non-Fatal               1.366667
                  UNKWOWN       Fatal(1)                0.000000
Curtis            Reciprocating Non-Fatal               3.000000
De Havilland      Turbo Prop    Non-Fatal               4.000000
Embraer           Turbo Prop    Incident                2.000000
Enstrom           Reciprocating Non-Fatal               1.000000
Grumman           Reciprocating Fatal(2)                0.000000
                                Non-Fatal               1.000000
Hughes            Reciprocating Non-Fatal               1.000000
Lockheed          Turbo Fan     Incident              149.000000
Maule             Reciprocating Non-Fatal               2.000000
Mcdonnell Douglas Turbo Fan     Non-Fatal              44.000000
Mooney            Reciprocating Fatal(1)                0.000000
                                Non-Fatal               2.000000
Navion            Reciprocating Fatal(1)                0.000000
                                Fatal(3)                0.000000
North American    Reciprocating Non-Fatal               0.000000
Piper             Reciprocating Fatal(1)                0.000000
                                Fatal(2)                0.000000
                                Fatal(4)                0.000000
                                Incident                1.000000
                                Non-Fatal               1.363636
Quickie           Reciprocating Non-Fatal               1.000000
Rockwell          Reciprocating Fatal(2)                0.000000
                                Incident                1.000000
Schleicher        Unknown       Non-Fatal               1.000000
Smith             Reciprocating Non-Fatal               2.000000
Stinson           Reciprocating Fatal(2)                0.000000
Swearingen        Turbo Prop    Non-Fatal              12.000000

                                                 Total.Minor.Injuries
Make              Engine.Type   Injury.Severity
Aerospatiale      Turbo Shaft   Non-Fatal                    0.000000
Air Tractor       Reciprocating Non-Fatal                    0.000000
Bede Aircraft     Reciprocating Fatal(1)                     0.000000
Beech             Reciprocating Fatal(2)                     0.000000
                                Non-Fatal                    0.000000
Beechcraft        Reciprocating Fatal(1)                     0.000000
Bell              Turbo Shaft   Non-Fatal                    0.000000
Bell Helicopter   Turbo Shaft   Fatal(1)                     0.000000
Bellanca          Reciprocating Non-Fatal                    1.500000
Boeing            Reciprocating Non-Fatal                    0.000000
                  Turbo Fan     Fatal(78)                    3.000000
Cessna            Reciprocating Fatal(1)                     0.250000
                                Fatal(2)                     0.000000
                                Fatal(3)                     0.000000
                                Fatal(4)                     0.500000
                                Fatal(8)                     0.000000
                                Non-Fatal                    0.448276
                  UNKWOWN       Fatal(1)                          NaN
Curtis            Reciprocating Non-Fatal                    0.000000
De Havilland      Turbo Prop    Non-Fatal                    0.000000
Embraer           Turbo Prop    Incident                     0.000000
Enstrom           Reciprocating Non-Fatal                    0.000000
Grumman           Reciprocating Fatal(2)                     0.000000
                                Non-Fatal                    0.000000
Hughes            Reciprocating Non-Fatal                    0.000000
Lockheed          Turbo Fan     Incident                     0.000000
Maule             Reciprocating Non-Fatal                    0.000000
Mcdonnell Douglas Turbo Fan     Non-Fatal                    1.000000
Mooney            Reciprocating Fatal(1)                     0.000000
                                Non-Fatal                    0.000000
Navion            Reciprocating Fatal(1)                     0.000000
                                Fatal(3)                     0.000000
North American    Reciprocating Non-Fatal                    3.000000
Piper             Reciprocating Fatal(1)                     0.000000
                                Fatal(2)                     0.000000
                                Fatal(4)                     0.000000
                                Incident                     0.000000
                                Non-Fatal                    0.272727
Quickie           Reciprocating Non-Fatal                    0.000000
Rockwell          Reciprocating Fatal(2)                     0.000000
                                Incident                     0.000000
Schleicher        Unknown       Non-Fatal                    0.000000
Smith             Reciprocating Non-Fatal                    0.000000
Stinson           Reciprocating Fatal(2)                     0.000000
Swearingen        Turbo Prop    Non-Fatal                    2.000000

##Tableau presentation

[https://public.tableau.com/authoring/vayaya/Weathercontributiontoinjuries]

[https]://(public.tableau.com/authoring/vayaya/Weathercontributiontoinjuries)